plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ratlab'
    compileSdk 34

    defaultConfig {
        applicationId "com.ratlab"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.11.0'
    implementation 'org.json:json:20231013'
}
